---
- hosts: static_server
  become: yes
  vars_files:
    - vars/users.yml
    - vars/nginx.yml
  roles:
    - role: users
    - role: zsh
    - role: ssh
    - role: packages
    - role: nginx
    - role: static